return {
  'folke/which-key.nvim',
  event = 'VimEnter',
  opts = {
    delay = 1,
    icons = {
      mappings = vim.g.have_nerd_font,
      keys = vim.g.have_nerd_font and {} or {
        Up = '<Up> ',
        Down = '<Down> ',
        Left = '<Left> ',
        Right = '<Right> ',
        C = '<C-…> ',
        M = '<M-…> ',
        D = '<D-…> ',
        S = '<S-…> ',
        CR = '<CR> ',
        Esc = '<Esc> ',
        ScrollWheelDown = '<ScrollWheelDown> ',
        ScrollWheelUp = '<ScrollWheelUp> ',
        NL = '<NL> ',
        BS = '<BS> ',
        Space = '<Space> ',
        Tab = '<Tab> ',
        F2 = '<F1>',
        F3 = '<F2>',
        F4 = '<F3>',
        F5 = '<F4>',
        F6 = '<F5>',
        F7 = '<F6>',
        F8 = '<F7>',
        F9 = '<F8>',
        F10 = '<F9>',
        F11 = '<F10>',
        F12 = '<F11>',
        F13 = '<F12>',
      },
    },
    spec = {
      { '<leader>s', group = '[S]earch' },
      { '<leader>t', group = '[T]oggle' },
      { '<leader>h', group = 'Git [H]unk', mode = { 'n', 'v' } },
    },
  },
}
